SELECT LENGTH('SQL Expert') AS LEN FROM DUAL;

DESC DUAL;

SELECT PLAYER_NAME || '축구선수' AS 선수명 FROM player;

SELECT STADIUM_ID, DDD || ')' || TEL AS TEL, LENGTH (DDD || '-' || TEL) AS T_LEN FROM STADIUM;

SELECT ENAME, ROUND(SAL/12, 1) AS SAL_ROUND, TRUNC(SAL/12, 1) AS SAL_TRUNC FROM EMP;